name: Java CI with Maven (Quarkus)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission to mvnw
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw clean install

      - name: Run Tests
        run: ./mvnw test
